# ah
name: M.H.M.U.

# basic
verbose: true
silent: false

# input
data: [items.csv]

# output
stub: items
overwrite: false
backup: true

# sql
hostname: 127.0.0.1
database: xidb
username: root
password: ????
fail: true

# broker
restock: 3600
tick: 30

# scrub
server: bahamut
threads: -1
itemids: []
stock_single: 10
stock_stacks: 10
urls: []
