name: pydarkstar

channels:
  - defaults

dependencies:
  - beautiful-soup=4.3.2=py34_0
  - openssl=1.0.2k=0
  - pip=9.0.1=py34_1
  - pymysql=0.7.9=py34_0
  - python=3.4.5=0
  - pyyaml=3.12=py34_0
  - readline=6.2=2
  - setuptools=27.2.0=py34_0
  - sqlalchemy=1.1.5=py34_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py34_0
  - xz=5.2.2=1
  - yaml=0.1.6=0
  - zlib=1.2.8=3
  - pip:
    - beautifulsoup4==4.3.2
